# Generated by Django 5.2.14 on 2026-05-27 06:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=255)),
                ('subtitle_card', models.CharField(max_length=255)),
                ('subtitle_page', models.CharField(max_length=255)),
                ('description_card', models.TextField(blank=True, null=True)),
                ('description_page', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('conditioner', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
        ),
    ]
