# Generated by Django 5.2.14 on 2026-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='shower',
            field=models.BooleanField(default=False),
        ),
    ]
